version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    logging:
      driver: none
    ports:
      - "6379:6379"
    networks:
      app_net:
        ipv4_address: 192.168.0.5

  movie_store_app:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate --fake-initial && python manage.py migrate  && python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/movie_store
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      postgres_db: 
        condition: service_healthy
    networks:
      app_net:
        ipv4_address: 192.168.0.4

  postgres_db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_DB=movies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.0.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    logging:
      driver: none
    environment:
      PGADMIN_DEFAULT_EMAIL: grigorispapapostolou1994@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    networks:
      app_net:
        ipv4_address: 192.168.0.3

  celery:
    restart: always
    logging:
      driver: none
    build:
      context: .
    command: celery -A movie_store worker -l DEBUG
    volumes:
      - .:/movie_store
    container_name: celery
    depends_on:
      - postgres_db
      - redis
      - movie_store_app
    networks:
      app_net:
        ipv4_address: 192.168.0.6

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1